apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result
  name: result-deplt
  namespace: xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: eloip13009/voting-fila3:result
      # - image: europe-west9-docker.pkg.dev/tuto-terraform-406010/voting-app-repo/result
      # - image: gitlab-registry.imt-atlantique.fr/login-nuage/project-code/result
      # - image: result
        # imagePullPolicy: Never
        name: result-container
        ports:
        - containerPort: 80
          name: result-port
        livenessProbe:
          httpGet:
            path: /
            port: result-port
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 2
          initialDelaySeconds: 5
